defaults:
  actions:
    queue:
      method: squash
      commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body }}

queue_rules:
  - name: default
    conditions:
      # add checks
      - author=ophiryael
    batch_size: 5
    allow_inplace_checks: false

  - name: urgent
    conditions:
      # add checks
      - author=ophiryael
    batch_size: 5
    allow_inplace_checks: false

pull_request_rules:
  - name: automatic merge default priority PRs
    conditions:
      # add checks
      - base=master
      # - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label=merge when ready
    actions:
      queue:
        name: default
        priority: medium

  - name: automatic merge urgent priority PRs
    conditions:
      # add checks
      - base=master
      # - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label=merge when ready
      - label=urgent priority
    actions:
      queue:
        name: urgent
        priority: high

  - name: warn on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: "@{{author}} This PR is now in conflict"
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: warn on CI failure for urgent merge
    conditions:
      - label=urgent priority
      - "#check-failure>0"
    actions:
      comment:
        message: "@{{author}} Your urgent priority PR is failing CI"
