name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  sleep:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.title, 'merge-queue') }}
    steps:
      - name: Sleep for 1 minute
        run: if (( RANDOM % 2 )); then return  0; else return  1; fi
